### ISSUE TITLE
Can't make noobaa v5.6.0

### ISSUE THREAD

**Issue by djjudas21** [noobaa/homebrew-noobaa#28] opened 2021-03-12 09:43 UTC
Following the instructions but I can't get this to build properly:

```
[jonathan@poseidon ~]$ brew tap noobaa/noobaa
[jonathan@poseidon ~]$ brew install noobaa
==> Installing noobaa from noobaa/noobaa
==> Cloning https://github.com/noobaa/noobaa-operator.git
Updating /home/jonathan/.cache/Homebrew/noobaa--git
==> Checking out tag v5.6.0
HEAD is now at 706b32a Merge pull request #467 from dannyzaken/danny-5.6
HEAD is now at 706b32a Merge pull request #467 from dannyzaken/danny-5.6
==> go mod vendor
==> go generate
Last 15 lines from /home/jonathan/.cache/Homebrew/Logs/noobaa/02.go:
open vendor/github.com/imdario/mergo/doc.go: no such file or directory
# k8s.io/client-go/util/homedir
open vendor/k8s.io/client-go/util/homedir/homedir.go: no such file or directory
# sigs.k8s.io/controller-runtime/pkg/log
open vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go: no such file or directory
# golang.org/x/net/http/httpguts
open vendor/golang.org/x/net/http/httpguts/guts.go: no such file or directory
# github.com/pkg/errors
open vendor/github.com/pkg/errors/errors.go: no such file or directory
# sigs.k8s.io/yaml
open vendor/sigs.k8s.io/yaml/fields.go: no such file or directory
go build github.com/modern-go/reflect2: /home/linuxbrew/.linuxbrew/Cellar/go/1.16_1/libexec/pkg/tool/linux_amd64/asm: chdir /tmp/noobaa-20210312-377311-1t10eho/src/github.com/noobaa/noobaa-operator/vendor/github.com/modern-go/reflect2: no such file or directory
✅ vendor
make: *** [Makefile:95: pkg/bundle/deploy.go] Error 2
main.go:6: running "make": exit status 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/noobaa/homebrew-noobaa/issues
```

**Comment by guymguym** [comment] 2021-03-12 09:57
Hey @djjudas21 thanks for reporting on your experience!

Seems like the bottle we created for it is not applicable for you for some reason so it tries to build from source.

Which Mac version are you using? And which golang version do you have?

**Comment by djjudas21** [comment] 2021-03-12 10:15
Thanks for the response @guymguym. I'm on Linux.

```
[jonathan@poseidon ~]$ brew info go
go: stable 1.16 (bottled), HEAD
Open source programming language to build simple/reliable/efficient software
https://golang.org
/home/linuxbrew/.linuxbrew/Cellar/go/1.16_1 (9,936 files, 482.6MB) *
  Poured from bottle on 2021-03-02 at 19:29:37
From: https://github.com/Homebrew/linuxbrew-core/blob/HEAD/Formula/go.rb
License: BSD-3-Clause
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 4,001 (30 days), 13,254 (90 days), 42,020 (365 days)
install-on-request: 1,883 (30 days), 5,110 (90 days), 17,460 (365 days)
build-error: 0 (30 days)
```

```
[jonathan@poseidon ~]$ brew --version
Homebrew 3.0.5
Homebrew/homebrew-core (git revision 16829444381; last commit 2021-03-12)
Homebrew/homebrew-cask (git revision bb9350cc0e; last commit 2021-03-12)
```

**Comment by djjudas21** [comment] 2021-03-12 10:17
I've used this noobaa package on other Linux systems in the past, although I'm not sure what version of the noobaa package or go was on that system.

**Comment by guymguym** [comment] 2021-03-17 10:23
@djjudas21 Just tested on Fedora 33 and it works - so I wonder what has changed for your setup

```
[gu@Fedora33 ~]$ brew --version
Homebrew 3.0.7
Homebrew/homebrew-core (git revision 2e24069f93f; last commit 2021-03-17)

[gu@Fedora33 ~]$ brew install noobaa
==> Installing noobaa from noobaa/noobaa
==> Downloading https://linuxbrew.bintray.com/bottles/go-1.16.2_1.x86_64_linux.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/ac/ac0418ec93d70e6f4a38a6f6a99ca49f4d323cf01e88bb14e807fb2ddbc225d5?__gda__=exp=1615974917
######################################################################## 100.0%
==> Cloning https://github.com/noobaa/noobaa-operator.git
Cloning into '/home/gu/.cache/Homebrew/noobaa--git'...
==> Checking out tag v5.6.0
HEAD is now at 706b32a Merge pull request #467 from dannyzaken/danny-5.6
==> Installing dependencies for noobaa/noobaa/noobaa: go
==> Installing noobaa/noobaa/noobaa dependency: go
==> Pouring go-1.16.2_1.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/go/1.16.2_1: 9,944 files, 482.7MB
==> Installing noobaa/noobaa/noobaa
==> go mod vendor
==> go generate
==> go build
🍺  /home/linuxbrew/.linuxbrew/Cellar/noobaa/5.6.0: 3 files, 52.2MB, built in 2 minutes 27 seconds
```

**Comment by djjudas21** [comment] 2021-03-18 10:23
OK so your platform is also building from source and not using the bottle. So we can narrow down the problem to something with the go environment. I've got golang installed from brew, not the system package manager.

**Comment by guymguym** [comment] 2021-03-18 11:03
@djjudas21 Right, we didn't provide a bottle for linux, only Mac, so building from source it is.
Brew dependency on go should always use the golang installed from brew and not the platform package manager.
But environment variables such as GOROOT or GOHOME or GOPROXY or GO111MODULES etc might interfere.
Can you check if you have any such env variables defined globally?

**Comment by djjudas21** [comment] 2021-03-18 11:11
I don't have any GO-related env vars, as I don't use go for anything else, only a handful of projects from brew, like `kubernetes-cli` and `helm`.

```
[jonathan@poseidon ~]$ printenv | grep GO
```

**Comment by guymguym** [comment] 2021-03-18 11:20
Perhaps you tried already but if not - can you try `brew upgrade` and then `brew install noobaa --verbose` again to see if this happened to be transient?

I wonder what were the errors in `go generate` step before all those "no such file or directory" errors - perhaps `go mod vendor` did not work well and all the vendor code got to a different path.

**Comment by djjudas21** [comment] 2021-03-18 11:24
I already tried `brew update && brew upgrade` but here's the output of the verbose install attempt:

```
[jonathan@poseidon ~]$ brew install noobaa --verbose
==> Installing noobaa from noobaa/noobaa
==> Cloning https://github.com/noobaa/noobaa-operator.git
git --git-dir /home/jonathan/.cache/Homebrew/noobaa--git/.git status -s
Updating /home/jonathan/.cache/Homebrew/noobaa--git
git config remote.origin.url https://github.com/noobaa/noobaa-operator.git
git config remote.origin.fetch \+refs/tags/v5.6.0:refs/tags/v5.6.0
git config remote.origin.tagOpt --no-tags
git --git-dir /home/jonathan/.cache/Homebrew/noobaa--git/.git rev-parse -q --verify v5.6.0\^\{commit\}
==> Checking out tag v5.6.0
git checkout -f v5.6.0 --
HEAD is now at 706b32a Merge pull request #467 from dannyzaken/danny-5.6
git reset --hard v5.6.0 --
HEAD is now at 706b32a Merge pull request #467 from dannyzaken/danny-5.6
git --git-dir /home/jonathan/.cache/Homebrew/noobaa--git/.git rev-parse -q --verify HEAD
git --git-dir /home/jonathan/.cache/Homebrew/noobaa--git/.git rev-parse -q --verify HEAD
hdiutil imageinfo -format /home/jonathan/.cache/Homebrew/noobaa--git
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/.travis.yml /tmp/d20210318-1124395-13fzgnw/.travis.yml
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/.travis/. /tmp/d20210318-1124395-13fzgnw/.travis
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/devenv.sh /tmp/d20210318-1124395-13fzgnw/devenv.sh
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/test/. /tmp/d20210318-1124395-13fzgnw/test
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/Makefile /tmp/d20210318-1124395-13fzgnw/Makefile
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/PROJECT /tmp/d20210318-1124395-13fzgnw/PROJECT
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/LICENSE /tmp/d20210318-1124395-13fzgnw/LICENSE
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/README.md /tmp/d20210318-1124395-13fzgnw/README.md
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/cmd/. /tmp/d20210318-1124395-13fzgnw/cmd
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/deploy/. /tmp/d20210318-1124395-13fzgnw/deploy
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/go.sum /tmp/d20210318-1124395-13fzgnw/go.sum
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/tools.go /tmp/d20210318-1124395-13fzgnw/tools.go
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/.gitignore /tmp/d20210318-1124395-13fzgnw/.gitignore
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/build/. /tmp/d20210318-1124395-13fzgnw/build
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/version/. /tmp/d20210318-1124395-13fzgnw/version
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/doc/. /tmp/d20210318-1124395-13fzgnw/doc
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/main.go /tmp/d20210318-1124395-13fzgnw/main.go
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/pkg/. /tmp/d20210318-1124395-13fzgnw/pkg
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/.git/. /tmp/d20210318-1124395-13fzgnw/.git
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/.dockerignore /tmp/d20210318-1124395-13fzgnw/.dockerignore
cp -pR /home/jonathan/.cache/Homebrew/noobaa--git/go.mod /tmp/d20210318-1124395-13fzgnw/go.mod
cp -pR /tmp/d20210318-1124395-13fzgnw/go.mod /tmp/noobaa-20210318-1124395-1io7zlk/go.mod
cp -pR /tmp/d20210318-1124395-13fzgnw/.dockerignore /tmp/noobaa-20210318-1124395-1io7zlk/.dockerignore
cp -pR /tmp/d20210318-1124395-13fzgnw/.git/. /tmp/noobaa-20210318-1124395-1io7zlk/.git
cp -pR /tmp/d20210318-1124395-13fzgnw/pkg/. /tmp/noobaa-20210318-1124395-1io7zlk/pkg
cp -pR /tmp/d20210318-1124395-13fzgnw/main.go /tmp/noobaa-20210318-1124395-1io7zlk/main.go
cp -pR /tmp/d20210318-1124395-13fzgnw/doc/. /tmp/noobaa-20210318-1124395-1io7zlk/doc
cp -pR /tmp/d20210318-1124395-13fzgnw/version/. /tmp/noobaa-20210318-1124395-1io7zlk/version
cp -pR /tmp/d20210318-1124395-13fzgnw/build/. /tmp/noobaa-20210318-1124395-1io7zlk/build
cp -pR /tmp/d20210318-1124395-13fzgnw/.gitignore /tmp/noobaa-20210318-1124395-1io7zlk/.gitignore
cp -pR /tmp/d20210318-1124395-13fzgnw/tools.go /tmp/noobaa-20210318-1124395-1io7zlk/tools.go
cp -pR /tmp/d20210318-1124395-13fzgnw/go.sum /tmp/noobaa-20210318-1124395-1io7zlk/go.sum
cp -pR /tmp/d20210318-1124395-13fzgnw/deploy/. /tmp/noobaa-20210318-1124395-1io7zlk/deploy
cp -pR /tmp/d20210318-1124395-13fzgnw/cmd/. /tmp/noobaa-20210318-1124395-1io7zlk/cmd
cp -pR /tmp/d20210318-1124395-13fzgnw/README.md /tmp/noobaa-20210318-1124395-1io7zlk/README.md
cp -pR /tmp/d20210318-1124395-13fzgnw/LICENSE /tmp/noobaa-20210318-1124395-1io7zlk/LICENSE
cp -pR /tmp/d20210318-1124395-13fzgnw/PROJECT /tmp/noobaa-20210318-1124395-1io7zlk/PROJECT
cp -pR /tmp/d20210318-1124395-13fzgnw/Makefile /tmp/noobaa-20210318-1124395-1io7zlk/Makefile
cp -pR /tmp/d20210318-1124395-13fzgnw/test/. /tmp/noobaa-20210318-1124395-1io7zlk/test
cp -pR /tmp/d20210318-1124395-13fzgnw/devenv.sh /tmp/noobaa-20210318-1124395-1io7zlk/devenv.sh
cp -pR /tmp/d20210318-1124395-13fzgnw/.travis/. /tmp/noobaa-20210318-1124395-1io7zlk/.travis
cp -pR /tmp/d20210318-1124395-13fzgnw/.travis.yml /tmp/noobaa-20210318-1124395-1io7zlk/.travis.yml
chmod -Rf +w /tmp/d20210318-1124395-13fzgnw
git --git-dir /home/jonathan/.cache/Homebrew/noobaa--git/.git show -s --format=\%cD
==> go mod vendor
go: downloading github.com/spf13/cobra v0.0.5
go: downloading k8s.io/apimachinery v0.17.4
go: downloading github.com/sirupsen/logrus v1.5.0
go: downloading k8s.io/api v0.17.4
go: downloading k8s.io/client-go v0.17.4
go: downloading sigs.k8s.io/controller-runtime v0.5.2
go: downloading sigs.k8s.io/yaml v1.1.0
go: downloading k8s.io/code-generator v0.17.4
go: downloading github.com/go-openapi/spec v0.19.4
go: downloading github.com/kube-object-storage/lib-bucket-provisioner v0.0.0-20200107223247-51020689f1fb
go: downloading k8s.io/kubectl v0.17.4
go: downloading github.com/openshift/custom-resource-status v0.0.0-20190801200128-4c95b3a336cd
go: downloading k8s.io/apiextensions-apiserver v0.17.4
go: downloading k8s.io/cli-runtime v0.17.4
go: downloading k8s.io/kube-openapi v0.0.0-20191107075043-30be4d16710a
go: downloading k8s.io/gengo v0.0.0-20191010091904-7fa3014cb28f
go: downloading github.com/blang/semver v3.5.1+incompatible
go: downloading github.com/operator-framework/operator-lifecycle-manager v0.0.0-20200321030439-57b580e57e88
go: downloading github.com/operator-framework/operator-sdk v0.17.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading cloud.google.com/go v0.49.0
go: downloading github.com/Azure/azure-sdk-for-go v39.2.0+incompatible
go: downloading github.com/Azure/azure-storage-blob-go v0.8.0
go: downloading github.com/Azure/go-autorest v13.3.2+incompatible
go: downloading github.com/Azure/go-autorest/autorest v0.9.4
go: downloading github.com/asaskevich/govalidator v0.0.0-20200108200545-475eaeb16496
go: downloading cloud.google.com/go/storage v1.3.0
go: downloading github.com/Azure/go-autorest/autorest/adal v0.8.1
go: downloading github.com/Azure/go-autorest/autorest/to v0.3.1-0.20191028180845-3492b2aff503
go: downloading github.com/aws/aws-sdk-go v1.25.48
go: downloading github.com/coreos/go-semver v0.3.0
go: downloading github.com/coreos/prometheus-operator v0.38.0
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading github.com/marstr/randname v0.0.0-20200428202425-99aca53a2176
go: downloading github.com/openshift/api v3.9.1-0.20190924102528-32369d4db2ad+incompatible
go: downloading github.com/openshift/cloud-credential-operator v0.0.0-20190614194054-1ccced634f6c
go: downloading github.com/rook/rook v1.1.2
go: downloading google.golang.org/api v0.14.0
go: downloading nhooyr.io/websocket v1.7.4
go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.2
go: downloading golang.org/x/sys v0.0.0-20200323222414-85ca7c5b95cd
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading github.com/gogo/protobuf v1.3.1
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading k8s.io/klog v1.0.0
go: downloading github.com/google/gofuzz v1.0.0
go: downloading k8s.io/utils v0.0.0-20191114200735-6ca3b61696b6
go: downloading github.com/evanphx/json-patch v4.5.0+incompatible
go: downloading github.com/go-logr/logr v0.1.0
go: downloading github.com/prometheus/client_golang v1.5.1
go: downloading gopkg.in/yaml.v2 v2.2.8
go: downloading github.com/go-openapi/jsonpointer v0.19.3
go: downloading github.com/go-openapi/jsonreference v0.19.3
go: downloading github.com/go-openapi/swag v0.19.5
go: downloading golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: downloading github.com/golang/groupcache v0.0.0-20191027212112-611e8accdfc9
go: downloading github.com/liggitt/tabwriter v0.0.0-20181228230101-89fcab3d43de
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/emicklei/go-restful v2.9.6+incompatible
go: downloading github.com/MakeNowJust/heredoc v0.0.0-20170808103936-bb23615498cd
go: downloading github.com/russross/blackfriday v1.5.2
go: downloading github.com/Azure/azure-pipeline-go v0.2.2
go: downloading github.com/ghodss/yaml v1.0.1-0.20190212211648-25d852aebe32
go: downloading github.com/pborman/uuid v1.2.0
go: downloading github.com/Azure/go-autorest/tracing v0.5.0
go: downloading github.com/Azure/go-autorest/logger v0.1.0
go: downloading github.com/Azure/go-autorest/autorest/date v0.2.0
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/googleapis/gax-go v2.0.2+incompatible
go: downloading github.com/googleapis/gax-go/v2 v2.0.5
go: downloading google.golang.org/genproto v0.0.0-20191115194625-c23dd37a84c9
go: downloading github.com/opencontainers/go-digest v1.0.0-rc1
go: downloading github.com/marstr/collection v1.0.1
go: downloading golang.org/x/net v0.0.0-20200822124328-c89045814202
go: downloading github.com/golang/protobuf v1.3.2
go: downloading github.com/googleapis/gnostic v0.3.1
go: downloading github.com/imdario/mergo v0.3.7
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/prometheus/common v0.9.1
go: downloading gomodules.xyz/jsonpatch/v2 v2.0.1
go: downloading github.com/PuerkitoBio/purell v1.1.1
go: downloading github.com/mailru/easyjson v0.7.0
go: downloading golang.org/x/tools v0.0.0-20200915031644-64986481280e
go: downloading golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
go: downloading github.com/gophercloud/gophercloud v0.6.0
go: downloading github.com/json-iterator/go v1.1.9
go: downloading github.com/docker/docker v1.4.2-0.20200203170920-46ec8731fbce
go: downloading github.com/mitchellh/go-wordwrap v1.0.0
go: downloading github.com/mattn/go-ieproxy v0.0.0-20191113090002-7c0f6868bffe
go: downloading github.com/markbates/inflect v1.0.4
go: downloading github.com/spf13/afero v1.2.2
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/rogpeppe/go-internal v1.5.0
go: downloading github.com/jstemmer/go-junit-report v0.9.1
go: downloading golang.org/x/exp v0.0.0-20191030013958-a1ab85dbe136
go: downloading golang.org/x/lint v0.0.0-20200302205851-738671d3881b
go: downloading honnef.co/go/tools v0.0.1-2019.2.3
go: downloading google.golang.org/grpc v1.27.0
go: downloading go.opencensus.io v0.22.2
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/docker/spdystream v0.0.0-20160310174837-449fdfce4d96
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/cespare/xxhash v1.1.0
go: downloading github.com/prometheus/procfs v0.0.8
go: downloading gopkg.in/fsnotify.v1 v1.4.7
go: downloading google.golang.org/appengine v1.6.5
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
go: downloading golang.org/x/text v0.3.3
go: downloading github.com/hashicorp/golang-lru v0.5.3
go: downloading github.com/google/go-cmp v0.4.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/gobuffalo/envy v1.7.0
go: downloading github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
go: downloading github.com/Azure/go-ansiterm v0.0.0-20170929234023-d6e3b3328b78
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading golang.org/x/mod v0.3.0
go: downloading github.com/joho/godotenv v1.3.0
go: downloading github.com/BurntSushi/toml v0.3.1
go: downloading github.com/Azure/go-autorest/autorest/validation v0.2.1-0.20191028180845-3492b2aff503
==> go generate
go mod tidy
mkdir -p pkg/bundle
go run pkg/bundler/bundler.go deploy/ pkg/bundle/deploy.go
go: downloading github.com/stretchr/testify v1.4.0
go: downloading github.com/onsi/ginkgo v1.11.0
go: downloading github.com/onsi/gomega v1.8.1
go: downloading github.com/gobwas/ws v1.0.2
go: downloading github.com/gorilla/websocket v1.4.1
go: downloading go.uber.org/multierr v1.5.0
go: downloading github.com/Azure/go-autorest/autorest/mocks v0.3.0
go: downloading gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15
go: downloading github.com/go-logr/zapr v0.1.1
go: downloading go.uber.org/zap v1.14.1
go: downloading github.com/elazarl/goproxy v0.0.0-20170405201442-c4fc26588b6e
go: downloading go.uber.org/atomic v1.6.0
go: downloading go.uber.org/tools v0.0.0-20190618225709-2cfd321de3ee
go: downloading cloud.google.com/go/bigquery v1.3.0
go: downloading cloud.google.com/go/datastore v1.0.0
go: downloading cloud.google.com/go/pubsub v1.0.1
go: downloading github.com/gobwas/pool v0.2.0
go: downloading github.com/gobwas/httphead v0.0.0-20180130184737-2c6c146eadee
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/kr/pretty v0.1.0
go: downloading gotest.tools v2.2.0+incompatible
go: downloading github.com/sergi/go-diff v1.0.0
go: downloading github.com/google/martian v2.1.0+incompatible
go: downloading github.com/fsnotify/fsnotify v1.4.7
go: downloading github.com/kr/text v0.1.0
go: downloading github.com/hpcloud/tail v1.0.0
go: downloading golang.org/x/sync v0.0.0-20200625203802-6e8e738ad208
go: downloading github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go mod vendor
# golang.org/x/net/http2
open vendor/golang.org/x/net/http2/ciphers.go: no such file or directory
# github.com/PuerkitoBio/purell
open vendor/github.com/PuerkitoBio/purell/purell.go: no such file or directory
# golang.org/x/net/context/ctxhttp
open vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go: no such file or directory
# k8s.io/apimachinery/pkg/version
open vendor/k8s.io/apimachinery/pkg/version/doc.go: no such file or directory
# k8s.io/client-go/util/connrotation
open vendor/k8s.io/client-go/util/connrotation/connrotation.go: no such file or directory
# k8s.io/client-go/tools/metrics
open vendor/k8s.io/client-go/tools/metrics/metrics.go: no such file or directory
# golang.org/x/time/rate
open vendor/golang.org/x/time/rate/rate.go: no such file or directory
# k8s.io/client-go/util/keyutil
open vendor/k8s.io/client-go/util/keyutil/key.go: no such file or directory
# github.com/golang/protobuf/proto
open vendor/github.com/golang/protobuf/proto/clone.go: no such file or directory
# k8s.io/utils/pointer
open vendor/k8s.io/utils/pointer/pointer.go: no such file or directory
# k8s.io/apimachinery/pkg/util/wait
open vendor/k8s.io/apimachinery/pkg/util/wait/doc.go: no such file or directory
# github.com/spf13/pflag
open vendor/github.com/spf13/pflag/bool.go: no such file or directory
# k8s.io/apimachinery/pkg/util/duration
open vendor/k8s.io/apimachinery/pkg/util/duration/duration.go: no such file or directory
# sigs.k8s.io/yaml
open vendor/sigs.k8s.io/yaml/fields.go: no such file or directory
# k8s.io/client-go/third_party/forked/golang/template
open vendor/k8s.io/client-go/third_party/forked/golang/template/exec.go: no such file or directory
go build github.com/modern-go/reflect2: /home/linuxbrew/.linuxbrew/Cellar/go/1.16.2_1/libexec/pkg/tool/linux_amd64/asm: chdir /tmp/noobaa-20210318-1124395-1io7zlk/src/github.com/noobaa/noobaa-operator/vendor/github.com/modern-go/reflect2: no such file or directory
# k8s.io/client-go/util/homedir
open vendor/k8s.io/client-go/util/homedir/homedir.go: no such file or directory
# github.com/pkg/errors
open vendor/github.com/pkg/errors/errors.go: no such file or directory
# sigs.k8s.io/controller-runtime/pkg/internal/log
open vendor/sigs.k8s.io/controller-runtime/pkg/internal/log/log.go: no such file or directory
go build golang.org/x/sys/unix: /home/linuxbrew/.linuxbrew/Cellar/go/1.16.2_1/libexec/pkg/tool/linux_amd64/asm: chdir /tmp/noobaa-20210318-1124395-1io7zlk/src/github.com/noobaa/noobaa-operator/vendor/golang.org/x/sys/unix: no such file or directory
✅ vendor
make: *** [Makefile:95: pkg/bundle/deploy.go] Error 2
main.go:6: running "make": exit status 2
/usr/bin/ruby -e puts\ RUBY_VERSION

==> Formula
Tap: noobaa/noobaa
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/noobaa/homebrew-noobaa/Formula/noobaa.rb
==> Configuration
HOMEBREW_VERSION: 3.0.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 59ada80ca740e72d29e625079395ee91cae4b3cf
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 1f7283aa35696651173514d827921e7ef7efc310
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :1
HOMEBREW_EDITOR: /usr/bin/vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit sandybridge
Clang: 11.0 build (parse error)
Git: 2.29.2 => /bin/git
Curl: 7.71.1 => /usr/bin/curl
Kernel: Linux 5.10.19-200.fc33.x86_64 x86_64 GNU/Linux
OS: Fedora release 33 (Thirty Three)
Host glibc: 2.32
/usr/bin/gcc: 10.2.1
/usr/bin/ruby -e puts\ RUBY_VERSION
/usr/bin/ruby: 2.7.2
glibc: N/A
gcc@5: N/A
xorg: N/A
==> ENV
HOMEBREW_CC: gcc-10
HOMEBREW_CXX: g++-10
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /home/linuxbrew/.linuxbrew
HOMEBREW_GIT: git
ACLOCAL_PATH: /home/linuxbrew/.linuxbrew/share/aclocal
PATH: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super:/home/linuxbrew/.linuxbrew/opt/go/bin:/home/linuxbrew/.linuxbrew/opt/binutils/bin:/usr/bin:/bin:/usr/sbin:/sbin:/home/linuxbrew/.linuxbrew/opt/gcc/bin

Error: noobaa/noobaa/noobaa 5.6.0 did not build
Logs:
     /home/jonathan/.cache/Homebrew/Logs/noobaa/01.go
     /home/jonathan/.cache/Homebrew/Logs/noobaa/00.options.out
     /home/jonathan/.cache/Homebrew/Logs/noobaa/02.go
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/noobaa/homebrew-noobaa/issues

/usr/bin/curl --disable --globoff --show-error --user-agent Linuxbrew/3.0.7\ \(Linux\;\ x86_64\ 5.10.19-200.fc33.x86_64\)\ curl/7.71.1 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/issues\?q=noobaa\+repo\%3Anoobaa\%2Fhomebrew-noobaa\+state\%3Aopen\+in\%3Atitle\&per_page=100 --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --dump-header /tmp/github_api_headers20210318-1123542-si34et
These open issues may also help:
Can't make noobaa v5.6.0 https://github.com/noobaa/homebrew-noobaa/issues/28
```

**Comment by djjudas21** [comment] 2021-03-22 22:13
I attempted to install on a different system, Fedora 33 again, and it failed in the same way:

```
[jonathan@latitude tagger]$ brew install noobaa/noobaa/noobaa
==> Tapping noobaa/noobaa
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/noobaa/homebrew-noobaa'...
remote: Enumerating objects: 117, done.
remote: Counting objects: 100% (117/117), done.
remote: Compressing objects: 100% (95/95), done.
remote: Total 207 (delta 50), reused 33 (delta 11), pack-reused 90
Receiving objects: 100% (207/207), 44.72 KiB | 11.18 MiB/s, done.
Resolving deltas: 100% (85/85), done.
Tapped 2 formulae (32 files, 167.7KB).
==> Installing noobaa from noobaa/noobaa
==> Cloning https://github.com/noobaa/noobaa-operator.git
Cloning into '/home/jonathan/.cache/Homebrew/noobaa--git'...
==> Checking out tag v5.6.0
HEAD is now at 706b32a Merge pull request #467 from dannyzaken/danny-5.6
==> go mod vendor
==> go generate
Last 15 lines from /home/jonathan/.cache/Homebrew/Logs/noobaa/02.go:
# k8s.io/apimachinery/pkg/api/resource
open vendor/k8s.io/apimachinery/pkg/api/resource/amount.go: no such file or directory
# k8s.io/apimachinery/pkg/runtime/schema
open vendor/k8s.io/apimachinery/pkg/runtime/schema/generated.pb.go: no such file or directory
# k8s.io/apimachinery/pkg/util/duration
open vendor/k8s.io/apimachinery/pkg/util/duration/duration.go: no such file or directory
# k8s.io/client-go/third_party/forked/golang/template
open vendor/k8s.io/client-go/third_party/forked/golang/template/exec.go: no such file or directory
# k8s.io/client-go/util/homedir
open vendor/k8s.io/client-go/util/homedir/homedir.go: no such file or directory
# sigs.k8s.io/controller-runtime/pkg/log
open vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go: no such file or directory
✅ vendor
make: *** [Makefile:95: pkg/bundle/deploy.go] Error 2
main.go:6: running "make": exit status 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/noobaa/homebrew-noobaa/issues

These open issues may also help:
Can't make noobaa v5.6.0 https://github.com/noobaa/homebrew-noobaa/issues/28
```

**Comment by guymguym** [comment] 2021-03-24 09:40
@djjudas21 Thanks for all the info! Now that I see the verbose output I think the problem is `HOMEBREW_MAKE_JOBS: 8` because the noobaa-operator makefile does not work well with parallel jobs. Sorry for all the confusion this caused.

I tried to fix it in the formula by adding `ENV.deparallelize` (https://docs.brew.sh/Formula-Cookbook#bad-makefiles):
https://github.com/noobaa/homebrew-noobaa/blob/81215d768d1e0393dd357497ec2669a2263cce9b/Formula/noobaa.rb#L18

Try to run `brew update` and `brew install noobaa` again now.
Hope this works!

**Comment by djjudas21** [comment] 2021-03-24 11:23
Awesome, can confirm this works for me now. Thanks for your effort :+1:

**Comment by guymguym** [comment] 2021-03-24 12:06
Thank you @djjudas21 ! I appreciate your help to debug this. Closing the issue.

**Closed as completed by guymguym** 2021-03-24 12:06 UTC
